config/routes.rb
Rails.application.routes.draw do
  resources :employees
  resources :companies do
    collection {post :import}
  end

  resources :invoices do
    resources :purchases, except: [:index, :show]
  end

  root to: 'static_pages#index'
  
  get   'about', to: 'static_pages#about'
  get   'contact', to: 'static_pages#contact'
  get   'privacy', to: 'static_pages#privacy'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/invoice.rb
# == Schema Information
#
# Table name: invoices
#
#  id          :integer          not null, primary key
#  company     :string
#  date        :datetime
#  status_type :string
#  tax         :decimal(, )
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  employee_id :integer          not null
#
# Indexes
#
#  index_invoices_on_employee_id  (employee_id)
#
# Foreign Keys
#
#  employee_id  (employee_id => employees.id)
#
class Invoice < ApplicationRecord
  belongs_to :employee
  has_many :purchases, dependent: :destroy
  validates :company, :status_type, presence: true
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: %i[ show edit update destroy ]

  # GET /invoices or /invoices.json
  def index
    @search = InvoiceSearch.new(params[:search])
    # @invoices = Invoice.all
    @invoices = @search.scope
  end

  # GET /invoices/1 or /invoices/1.json
  def show
    @purchases = @invoice.purchases
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices or /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to invoice_url(@invoice), notice: "Invoice was successfully created." }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1 or /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to invoice_url(@invoice), notice: "Invoice was successfully updated." }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1 or /invoices/1.json
  def destroy
    @invoice.destroy

    respond_to do |format|
      format.html { redirect_to invoices_url, notice: "Invoice was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def invoice_params
      params.require(:invoice).permit(:date, :company, :tax, :status_type, :employee_id)
    end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
<%= simple_form_for(@invoice) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :date %>
    <%= f.input :company %>
    <%= f.input :tax %>
    <%= f.association :employee, collection: Employee.order(:name), prompt: "Choose an Employee" %>
    <%= f.select(:status_type, options_for_select([['PAID', 'PAID'], ['PENDING', 'PENDING']]), { prompt: 'Choose a Status' }, class: 'form-control') %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/invoices/_invoice.html.erb
<tr>
  <td><%= invoice.date.strftime("%Y/%m/%d") %></td>
  <td><%= invoice.company %></td>
  <td><%= invoice.tax %></td>
  <td><%= invoice.employee.name %></td>
  <td><%= invoice.status_type %></td>
  <td><%= link_to 'Show', invoice, class: 'btn btn-default' %></td>
  <td><%= link_to 'Edit', edit_invoice_path(invoice), class: 'btn btn-default btn-success' %></td>
  <td><%= button_to 'Destroy', invoice, method: :delete, class: 'btn btn-default btn-danger', data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/invoices/edit.html.erb
<h1>Editing invoice</h1>

<%= render "form", invoice: @invoice %>

<br>

<div>
  <%= link_to "Show this invoice", @invoice %> |
  <%= link_to "Back to invoices", invoices_path %>
</div>

app/views/invoices/index.html.erb
<div class="row">
  <h1>Listing Invoices</h1>
  <div class="pull-right range-query">
    <%= form_tag invoices_path, method: :get do %>
      <%= text_field_tag 'search[date_from]', @search.date_from %>
      <%= text_field_tag 'search[date_to]', @search.date_to %>
      <%= submit_tag 'Search', class: 'btn btn-secondary search-button' %>
    <% end %>
    <%= link_to 'New Invoice', new_invoice_path, class: 'btn btn-primary' %>
  </div>
</div>

<div class="media">
  <div class="media-body">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Date</th>
          <th>Company</th>
          <th>Tax</th>
          <th>Salesperson</th>
          <th>Status</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <%= render @invoices %>
      </tbody>
    </table>
  </div>
</div>
<br>

app/views/invoices/new.html.erb
<h1>New invoice</h1>

<%= render "form", invoice: @invoice %>

<br>

<div>
  <%= link_to "Back to invoices", invoices_path %>
</div>

app/views/invoices/show.html.erb
<p>
  <strong>Date:</strong>
  <%= @invoice.date %>
</p>

<p>
  <strong>Company:</strong>
  <%= @invoice.company %>
</p>

<p>
  <strong>Tax:</strong>
  <%= @invoice.tax %>
</p>

<p>
  <strong>Salesperson:</strong>
  <%= @invoice.employee.name %>
</p>

<p>
  <strong>Status</strong>
  <%= @invoice.status_type %>
</p>

<div class="media">
  <div class="media-body">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th>Category</th>
          <th>Quantity</th>
          <th>Price</th>
          <th>Total</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% running_total = 0 %>
        <% @purchases.each do |purchase| %>
          <tr>
            <td><h4><%= purchase.name %></h4></td>
            <td><h4><%= purchase.category %></h4></td>
            <td><h4><%= purchase.quantity %></h4></td>
            <td><h4><%= number_to_currency(purchase.price) %></h4></td>
            <td><h4><%= number_to_currency(purchase.quantity * purchase.price) %></h4></td>
            <td><h4><%= link_to 'Edit', edit_invoice_purchase_path(@invoice, purchase) %></h4></td>
            <td><h4><%= link_to "Delete", [@invoice, purchase], method: :delete, data: { confirm: "Are your sure?"} %></h4></td>
            <% running_total = running_total + (purchase.quantity * purchase.price)  %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<%= link_to "Add new item", new_invoice_purchase_path(@invoice), class: 'pull-right' %>

<br>

<h4 class="pull-right">Invoice total: <%= number_to_currency(running_total) %></h4>

<%= link_to 'Edit', edit_invoice_path(@invoice) %> |
<%= link_to 'Back', invoices_path %>