config/routes.rb
Rails.application.routes.draw do
  resources :employees
  resources :companies do
    collection {post :import}
  end

  resources :invoices do
    resources :purchases, except: [:index, :show]
  end

  root to: 'static_pages#index'
  
  get   'about', to: 'static_pages#about'
  get   'contact', to: 'static_pages#contact'
  get   'privacy', to: 'static_pages#privacy'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/company.rb
# == Schema Information
#
# Table name: companies
#
#  id         :integer          not null, primary key
#  manager    :string
#  name       :string
#  status     :string
#  terms      :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Company < ApplicationRecord
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Company.create! row.to_hash
    end
  end

  def self.to_csv
    CSV.generate(headers: true) do |csv|
      csv << column_names

      all.each do |company|
        csv << company.attributes.values_at(*column_names)
      end
    end
  end    
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: %i[ show edit update destroy ]

  # GET /companies or /companies.json
  def index
    @companies = Company.all

    # for the export
    respond_to do |format|
      format.html
      format.csv { send_data @companies.to_csv, filename: "companies-#{Date.today}.csv" }
    end      
  end

  # GET /companies/1 or /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies or /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to company_url(@company), notice: "Company was successfully created." }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1 or /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to company_url(@company), notice: "Company was successfully updated." }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1 or /companies/1.json
  def destroy
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url, notice: "Company was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  def import
    # binding.irb
    Company.import(params[:file])
    redirect_to companies_path, notice: "Companies Added Successfully"
  end  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def company_params
      params.require(:company).permit(:name, :manager, :status, :terms)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_company.html.erb
<tr>
  <td><%= company.name %></td>
  <td><%= company.manager %></td>
  <td><%= company.status %></td>
  <td><%= company.terms %></td>
  <td><%= link_to 'Show', company, class: 'btn btn-default' %></td>
  <td><%= link_to 'Edit', edit_company_path(company), class: 'btn btn-default btn-success' %></td>
  <td><%= button_to 'Destroy', company, method: :delete, class: 'btn btn-default btn-danger', data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/companies/_form.html.erb
<%= simple_form_for(@company) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :manager %>
    <%= f.input :status %>
    <%= f.input :terms %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render "form", company: @company %>

<br>

<div>
  <%= link_to "Show this company", @company %> |
  <%= link_to "Back to companies", companies_path %>
</div>

app/views/companies/index.html.erb
<h1>Companies</h1>

<div class="media">
  <div class="media-body">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th>Manager</th>
          <th>Status</th>
          <th>Terms</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <%= render @companies %>
      </tbody>
    </table>
  </div>
</div>
<br>

<h3>Import Companies</h3>
<%= form_tag import_companies_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Upload Companies" %>
<% end %>

<h3>Download File</h3>
<%= link_to "Report", companies_path(format: "csv"), class: 'btn btn-secondary' %>

<%= link_to 'New Company', new_company_path, class: 'btn btn-primary' %>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render "form", company: @company %>

<br>

<div>
  <%= link_to "Back to companies", companies_path %>
</div>

app/views/companies/show.html.erb
<%= render @company %>

<div>
  <%= link_to "Edit this company", edit_company_path(@company) %> |
  <%= link_to "Back to companies", companies_path %>

  <%= button_to "Destroy this company", @company, method: :delete %>
</div>